UPDATE `config` SET `type`='enum', `type_values`='student=Student|project=Project' WHERE `var`='regfee_per' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='participant_student_foodreq' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='usedivisionselector' AND `year`!='-1';
UPDATE `config` SET `type`='enum', `type_values`='none=None|date=By Date|registration=With Registration' WHERE `var`='specialawardnomination' AND `year`!='-1';
UPDATE `config` SET `type`='enum', `type_values`='open=Open|singlepassword=Single Password|schoolpassword=School Password|invite=Invite|openorinvite=Open or Invite' WHERE `var`='participant_registration_type' AND `year`!='-1';
UPDATE `config` SET `type`='enum', `type_values`='open=Open|singlepassword=Single Password|invite=Invite' WHERE `var`='judge_registration_type' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='participant_student_tshirt' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='filterdivisionbycategory' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='participant_student_personal' AND `year`!='-1';
UPDATE `config` SET `type`='enum', `type_values`='open=Open|payment_pending=Payment Pending|complete=Complete' WHERE `var`='project_status' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='participant_project_table' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='participant_mentor' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='participant_project_electricity' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='tours_enable' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='scheduler_enable_sa_scheduling' AND `year`!='-1';
UPDATE `config` SET `type`='number', `type_values`='' WHERE `var`='participant_student_tshirt_cost' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='regfee_show_info' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='specialawardnomination_aftersignatures' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='judges_specialaward_enable' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='judges_specialaward_only_enable' AND `year`!='-1';
UPDATE `config` SET `type`='number', `type_values`='' WHERE `var`='judges_specialaward_min' AND `year`!='-1';
UPDATE `config` SET `type`='number', `type_values`='' WHERE `var`='judges_specialaward_max' AND `year`!='-1';
UPDATE `config` SET `type`='yesno', `type_values`='' WHERE `var`='participant_student_pronunciation' AND `year`!='-1';
UPDATE `config` SET `type`='number', `type_values`='' WHERE `var`='projects_per_special_award_judge' AND `year`!='-1';
