ALTER TABLE `reports` CHANGE `type` `type` ENUM( 'student', 'judge', 'award', 'committee', 'school', 'volunteer', 'tour', 'fair' ) NOT NULL DEFAULT 'student';

INSERT INTO `reports` (`id`, `system_report_id`, `name`, `desc`, `creator`, `type`) VALUES
	('', '46', 'Feeder Fairs -- All Stats', 'All feeder fair statistics in CSV', 'The Grant Brothers', 'fair');
INSERT INTO `reports_items` (`id`, `reports_id`, `type`, `ord`, `field`, `value`, `x`, `y`, `w`, `h`, `lines`, `face`, `align`) VALUES 
	('', LAST_INSERT_ID(), 'option', 0, 'type', 'csv', 0, 0, 0, 0, 0, '', ''),
	('', LAST_INSERT_ID(), 'option', 1, 'group_new_page', 'no', 0, 0, 0, 0, 0, '', ''),
	('', LAST_INSERT_ID(), 'option', 2, 'allow_multiline', 'no', 0, 0, 0, 0, 0, '', ''),
	('', LAST_INSERT_ID(), 'option', 3, 'fit_columns', 'no', 0, 0, 0, 0, 0, '', ''),
	('', LAST_INSERT_ID(), 'option', 4, 'label_box', 'no', 0, 0, 0, 0, 0, '', ''),
	('', LAST_INSERT_ID(), 'option', 5, 'field_box', 'no', 0, 0, 0, 0, 0, '', ''),
	('', LAST_INSERT_ID(), 'option', 6, 'label_fairname', 'no', 0, 0, 0, 0, 0, '', ''),
	('', LAST_INSERT_ID(), 'option', 7, 'label_logo', 'no', 0, 0, 0, 0, 0, '', ''),
	('', LAST_INSERT_ID(), 'option', 8, 'stock', 'fullpage', 0, 0, 0, 0, 0, '', ''),
	('', LAST_INSERT_ID(), 'col', 0, 'fair_name', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 1, 'fairstats_year', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 2, 'fairstats_start_date', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 3, 'fairstats_end_date', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 4, 'fairstats_budget', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 5, 'fairstats_address', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 6, 'fairstats_ysf_affiliation_complete', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 7, 'fairstats_charity', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 8, 'fairstats_scholarships', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 9, 'fairstats_male_1', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 10, 'fairstats_male_4', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 11, 'fairstats_male_7', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 12, 'fairstats_male_9', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 13, 'fairstats_male_11', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 14, 'fairstats_female_1', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 15, 'fairstats_female_4', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 16, 'fairstats_female_7', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 17, 'fairstats_female_9', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 18, 'fairstats_female_11', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 19, 'fairstats_projects_1', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 20, 'fairstats_projects_4', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 21, 'fairstats_projects_7', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 22, 'fairstats_projects_9', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 23, 'fairstats_projects_11', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 24, 'fairstats_firstnations', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 25, 'fairstats_students_atrisk', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 26, 'fairstats_schools_atrisk', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 27, 'fairstats_students_total', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 28, 'fairstats_schools_total', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 29, 'fairstats_schools_active', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 30, 'fairstats_students_public', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 31, 'fairstats_schools_public', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 32, 'fairstats_students_private', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 33, 'fairstats_schools_private', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 34, 'fairstats_schools_districts', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 35, 'fairstats_studentsvisiting', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 36, 'fairstats_publicvisiting', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 37, 'fairstats_teacherssupporting', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 38, 'fairstats_increasedinterest', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 39, 'fairstats_consideringcareer', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 40, 'fairstats_committee_members', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 41, 'fairstats_judges', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 42, 'fairstats_next_chair_name', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 43, 'fairstats_next_chairemail', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 44, 'fairstats_next_chair_hphone', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 45, 'fairstats_next_chair_bphone', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 46, 'fairstats_next_chair_fax', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 47, 'fairstats_delegate1', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 48, 'fairstats_delegate1_email', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 49, 'fairstats_delegate1_size', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 50, 'fairstats_delegate2', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 51, 'fairstats_delegate2_email', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 52, 'fairstats_delegate2_size', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 53, 'fairstats_delegate3', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 54, 'fairstats_delegate3_email', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 55, 'fairstats_delegate3_size', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 56, 'fairstats_delegate4', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 57, 'fairstats_delegate4_email', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'col', 58, 'fairstats_delegate4_size', '', 0, 0, 0, 0, 1, '', ' '),
	('', LAST_INSERT_ID(), 'sort', 0, 'fair_name', '', 0, 0, 0, 0, 1, '', ' ');

