ALTER TABLE `award_types` CHANGE `id` `id` INT( 10 ) UNSIGNED NOT NULL; 
ALTER TABLE `award_types` DROP PRIMARY KEY;
ALTER TABLE `award_types` ADD UNIQUE ( id, year );
INSERT INTO `award_types` VALUES (1, 'Divisional', 1, -1);
INSERT INTO `award_types` VALUES (2, 'Special', 2, -1);
INSERT INTO `award_types` VALUES (3, 'Interdisciplinary', 3, -1);
INSERT INTO `award_types` VALUES (4, 'Grand', 5, -1);
INSERT INTO `award_types` VALUES (5, 'Other', 4, -1);
INSERT INTO `award_types` VALUES (1, 'Divisional', 1, 2006);
INSERT INTO `award_types` VALUES (2, 'Special', 2, 2006);
INSERT INTO `award_types` VALUES (3, 'Interdisciplinary', 3, 2006);
INSERT INTO `award_types` VALUES (4, 'Grand', 5, 2006);
INSERT INTO `award_types` VALUES (5, 'Other', 4, 2006);
ALTER TABLE `pagetext` DROP INDEX `textname`; 
ALTER TABLE `pagetext` ADD UNIQUE(textname,year);
ALTER TABLE `pagetext` CHANGE `year` `year` INT NOT NULL DEFAULT '0';
INSERT INTO `pagetext` (`textname`,`text`,`year`) VALUES ('register_participants_main_instructions', 'Once all sections are complete, please print the signature page, obtain the required signatures, and mail the signature form, along with any required registration fees to:\r\nInsert address here\r\n\r\nYour forms must be received, post marked by <b>insert date here</b>.  Late entries will not be accepted', -1);
INSERT INTO `pagetext` (`textname`,`text`,`year`) VALUES ('index', 'Welcome to the online registration and management system for the fair.  Using the links on the left the public can register as a participant or register as a judge. \r\n\r\nThe committee can use the Fair Administration link to manage the fair, see who''s registered, renerate reports, etc.  \r\n\r\nThe SFIAB configuration link is for the committee webmaster to manage the configuration of the Science Fair In A Box for the fair.\r\n', -1);
ALTER TABLE `pagetext` ADD `lastupdate` DATETIME NOT NULL ;
