<?

$stats_data = array(
	'start_date' => array('manual' => true),
	'end_date' => array('manual' => true),
	'address' => array('manual' => true),
	'budget' => array('manual' => true),
	'ysf_affiliation_complete' => array('manual' => true),
	'charity' => array('manual' => true),
	'male_1' => array(),
	'male_4' => array(),
	'male_7' => array(),
	'male_9' => array(),
	'male_11' => array(),
	'female_1' => array(),
	'female_4' => array(),
	'female_7' => array(),
	'female_9' => array(),
	'female_11' => array(),
	'projects_1' => array(),
	'projects_4' => array(),
	'projects_7' => array(),
	'projects_9' => array(),
	'projects_11' => array(),
	'students_total' => array(),
	'schools_total' => array(),
	'schools_active' => array(),
	'students_public' => array(),
	'schools_public' => array(),
	'students_private' => array(),
	'schools_private' => array(),
	'schools_districts' => array(),
	'studentsvisiting' => array('manual' => true),
	'publicvisiting' => array('manual' => true),
	'firstnations' => array('manual' => true),
	'students_atrisk' => array(),
	'schools_atrisk' => array(),
	'teacherssupporting' => array('manual' => true),
	'increasedinterest' => array('manual' => true),
	'consideringcareer' => array('manual' => true),
	'committee_members' => array(),
	'judges' => array(),
	'next_chair_name' => array('manual' => true),
	'next_chair_email' => array('manual' => true),
	'next_chair_hphone' => array('manual' => true),
	'next_chair_bphone' => array('manual' => true),
	'next_chair_fax' => array('manual' => true),
	'scholarships' => array('manual' => true),
	'delegate1' => array('manual' => true),
	'delegate2' => array('manual' => true),
	'delegate3' => array('manual' => true),
	'delegate4' => array('manual' => true),
	'delegate1_email' => array('manual' => true),
	'delegate2_email' => array('manual' => true),
	'delegate3_email' => array('manual' => true),
	'delegate4_email' => array('manual' => true),
	'delegate1_size' => array('manual' => true),
	'delegate2_size' => array('manual' => true),
	'delegate3_size' => array('manual' => true),
	'delegate4_size' => array('manual' => true),
);
?>
